//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense_Tracker_EF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class expens
    {
        public int Id { get; set; }

        [Required]
        [DisplayName("Expense Title")]
        public string Title { get; set; }

        [Required]
        [DisplayName("Description")]
        public string Description { get; set; }

        [Required]
        [DisplayName("Expense Amount")]
        public Nullable<int> Amount { get; set; }

        [Required]
        [DisplayName("Category Name")]
        public Nullable<int> cid { get; set; }

        [Required]
        [DisplayName("Expense Date")]
        public Nullable<System.DateTime> ExpDate { get; set; }
    
        public virtual Category_Exp Category_Exp { get; set; }
    }
}
