//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense_Tracker_EF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Total_Expense_Limit
    {
        public int Id { get; set; }

        [Required]
        [DisplayName("Total Expense Limit")]
        public Nullable<int> TotalExpenseLimit { get; set; }
    }
}
